// Auto-generated by scripts/generate_schemes.go
// DO NOT EDIT MANUALLY
// Based on Mihomo version: v1.19.32-0.20260915165129-fbb674227d5c

#pragma once
#include <vector>
#include <string>

namespace mihomo {
    const std::vector<std::string> SUPPORTED_SCHEMES = {
        "hysteria",
        "hysteria2",
        "hy2",
        "hysteria2+realm",
        "hy2+realm",
        "tuic",
        "trojan",
        "vless",
        "vmess",
        "ss",
        "ssr",
        "socks",
        "socks5",
        "socks5h",
        "http",
        "https",
        "anytls",
        "mierus",
    };
}
